yushu/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    # 首页
    url(r'^$',views.index_home,name='index_home'),
    # 登录
    url(r'^login/$',views.login,name='index_login'),
    # 注册
    url(r'^register/$',views.index_register,name='index_register')
]

yushu/yushu/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^app/',include("App.urls",namespace='App'))
]

yushu/App/models.py
from django.db import models

# Create your models here.
from django.db import models
from datetime import datetime

from django.db.models import Model


class Book(models.Model):
    bookname = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    publisher = models.CharField(max_length=200)
    year = models.DateField()
    pages = models.IntegerField(max_length=50)
    price = models.FloatField(max_length=50)
    pack = models.CharField(max_length=50)
    ISBN = models.FloatField(max_length=100)
    jj = models.CharField(max_length=1000)
    tt = models.CharField(max_length=100)

    # def __str__(self):
    #     return self.
    class Meta:
        db_table = 'Book'

class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    sendnumber = models.IntegerField(max_length=50,blank=True,default=0)
    obtainnumber = models.IntegerField(max_length=50,blank=True,default=0)
    fishbean = models.CharField(max_length=50,blank=True,default=0)
    usertype = models.IntegerField(max_length=10,blank=True,default=0)

    class Meta:
        db_table = 'User'

class Transaction(models.Model):
    qiuid = models.IntegerField(max_length=50)
    shouusername = models.CharField(max_length=50)
    shoulocation = models.CharField(max_length=500)
    liuyan = models.CharField(max_length=1000)
    phone = models.IntegerField(max_length=50)
    ISBN = models.FloatField(max_length=50)
    bookname = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    tt = models.CharField(max_length=100)
    songid = models.IntegerField(max_length=50)
    listid = models.IntegerField(max_length=50)
    songusername = models.CharField(max_length=100)
    status = models.IntegerField(max_length=10,default=0)
    datatime = models.DateTimeField(default=datetime.now)

    class Meta:
        db_table = 'Transaction'

yushu/App/views.py
import hashlib
import re

from django.shortcuts import render

# Create your views
# 首页
from App.models import *


def index_home(request):
    return render(request,'index_home.html')
# 登录
def login(request):
    if request.method == 'POST':
        email = request.POST.get.email
        password = request.POST.get.password
        # 对密码进行hash1
        password = hashlib.sha1(password.encode('utf8')).hexdigest()









    return render(request,'index_login.html')
























# 注册
def index_register(request):
    if request.method == 'POST':
        a = 0
        b = 0
        c = 0
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        res = User.objects.all()
        print('aaaaaa',res)
        print('aaaaaaa',res)
        if not username:
            a = 1
        # elif username in res[0].username:
        elif User.objects.filter(username=username):
            a = 2
        elif not email:
            b = 1
        elif not re.match(r'^(\w{3,15})@(\w{2,5})\.(com|cn|net)$',str(email)):
            b = 2
        elif User.objects.filter(email=email):
            b = 3
        elif not re.match(r'[\w]{8,18}$',str(password)):
            c = 1
        elif str(password).isdigit():
            c = 2
        else:
            password = hashlib.sha1(password.encode('utf8')).hexdigest()
            user = User(username=username,password=password,email=email)
            user.save()
            request.session['username'] = username
            request.session['email'] = username
        if a > 0 or b > 0 or c > 0:
            return render(request,'index_register.html',context={
                'a':a,
                'b':b,
                'c':c
            })
        else:
            return render(request,'index_home.html',context={
                'username':username
            })
        #     return render(request, 'index_home.html')
    else:
        return render(request, 'index_register.html')

yushu/templates/book/detail.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>


    <title>鱼书</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">




    <link rel="stylesheet"
          href="/static/3rd/ui/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="shortcut icon"
          href="/static/images/icon.png">

    <link rel="stylesheet" href="/static/3rd/ui/remodal.css">
    <link rel="stylesheet" href="/static/3rd/ui/remodal-default-theme.css">
    <link rel="stylesheet" href="/static/css/book-detail.css">


<body>

    <div class="nav-self">
        <div style="padding-top: inherit" class="container">
            <form class="form-inline" action="/book/search" method="get">
                <div class="flex-vertical-center-height">
                    <div class="col-md-2  col-xs-3 logo">
                        <img src="/static/images/logo-yushu.png"/>
                    </div>
                    <div style="margin-left:20px;" class="col-md-7  col-xs-6 input-group">
                        <input name="q" type="text" placeholder="ISBN、图书名称"
                               class="form-control input-sm">
                        <span class="input-group-btn">
                            <input class="btn btn-search" type="submit" value="搜索"/>
                        </span>
                    </div>
                    <div class="col-md-3 col-xs-3" style="padding-right: 0">




                        <div class="container-height flex-vertical-center login-box">

                                <a href="/personal">苦海翻起爱恨的鱼书</a>
                                <a class="btn-end" href="/logout">注销</a>

                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="sub-nav flex-vertical-center">
        <div class="container" style="width: 100%">
            <div class="row">
                <div class="col-md-2 col-xs-3 col-md-offset-2">
                    <a id="recent" href="/"
                       class="flex-vertical-hor-center">
                        <img src="/static/images/upload.png"/>
                        <span>最近上传</span>
                    </a>
                </div>
                <div class="col-md-2 col-xs-3">
                    <a id="gifts" href="/my/gifts"
                       class="flex-vertical-hor-center">
                        <img src="/static/images/gift.png"/>
                        <span>赠送清单</span>
                    </a>
                </div>
                <div class="col-md-2 col-xs-3">
                    <a id="wishes" href="/my/wish"
                       class="flex-vertical-hor-center">
                        <img src="/static/images/wish.png"/>
                        <span>心愿清单</span>
                    </a>
                </div>
                <div class="col-md-2 col-xs-3">
                    <a id="pending" href="/pending"
                       class="flex-vertical-hor-center">
                        <img src="/static/images/fish.png"/>
                        <span>鱼漂</span>
                    </a>
                </div>
            </div>
        </div>
    </div>












<div class='container'>
    <div class="row">




    </div>


    <div class="row book-container my-detail-row" style="width: 100%">
        <div class="col-md-2">
            <img class="book-img" src="https://img3.doubanio.com/lpic/s3403254.jpg"/>
        </div>
        <div class="col-md-5 flex-vertical detail-con">
            <div>
                <h4>遇见未知的自己</h4>
            </div>
            <div class="description-font-margin">
                <div>
                    <span>作者:</span>
                    <span>张德芬</span>
                </div>
                <div>
                    <span>出版社:</span>
                    <span>华夏出版社</span>
                </div>
                <div>
                    <span>出版年：</span>
                    <span>2008-1</span>
                </div>
                <div>
                    <span>页数：</span>
                    <span>249</span>
                </div>
                <div>
                    <span>定价：</span>
                    <span>￥29.00</span>
                </div>
                <div>
                    <span>精装：</span>
                    <span>平装</span>
                </div>
                <div>
                    <span>ISBN：</span>
                    <span id="isbn">9787508044019</span>
                </div>

                    <div class="color-count">
                        <span>2人想要 / </span>
                        <span>4人可赠送</span>
                    </div>

            </div>
        </div>
    </div>
    <div style="margin-top:30px; display: flex" class="row ">

            <div class="col-md-3">
                <span class="bg-info">已添加至赠送清单</span>
            </div>

    </div>
    <div style="margin-top: 30px;" class="row">
        <div class="col-md-2"><span class="description-title">内容简介</span></div>
    </div>
    <div style="margin-top:15px;" class="row">
        <div class="col-md-11">
            <p class="description-font">故事从“冬天的雨夜，在荒郊野外的山区，一个没有手机、没有汽油的孤单女人”开始。\n若菱，自名校毕业，拥有令人羡慕的工作，但心中却不时的自问：为什么我不能拥有想要的生活？为什么我不快乐？我该如何当自己生命的主人？ 在一个下雨的冬夜，若菱巧遇一名智慧老者，在与智者数度交谈的过程中，她渐渐填补不快乐、挫败的心灵缺口，寻回最真实勇敢的自我…… 你会不会担心和若菱一样，让身体的疲惫失控于华丽的业绩之中？ 你是否也想遇见在你心中的智慧老者，穿越心事的重重黑纱，遇见全新的自己？</p>
        </div>
    </div>


        <div style="margin-top:30px; display: flex" class="row">
            <div class="col-md-3"><span class="description-title">向他们赠送此书</span></div>
        </div>
        <hr style="margin-top:5px;"/>

            <div style="margin-top:30px; display: flex" class="row">
                <div class="col-md-1" style="width: 11em;overflow: hidden;text-overflow: ellipsis;white-space: nowrap;">
                    z12z
                </div>
                <div class="col-md-2 description-font">
                    上传于2019-06-25
                </div>
                <div class="col-md-2">
                    <a class="btn-normal"
                       href="/satisfy/wish/938?isbn=9787508044019">向他赠送此书</a>
                </div>
            </div>

            <div style="margin-top:30px; display: flex" class="row">
                <div class="col-md-1" style="width: 11em;overflow: hidden;text-overflow: ellipsis;white-space: nowrap;">
                    嘻嘻
                </div>
                <div class="col-md-2 description-font">
                    上传于2019-06-25
                </div>
                <div class="col-md-2">
                    <a class="btn-normal"
                       href="/satisfy/wish/941?isbn=9787508044019">向他赠送此书</a>
                </div>
            </div>


    <div class="remodal" data-remodal-id="modal" role="dialog"
         aria-labelledby="modal1Title" aria-describedby="modal1Desc"
         data-remodal-options="closeOnOutsideClick: false">
        <button data-remodal-action="close" class="remodal-close"
                aria-label="Close"></button>
        <div>
            <h5 class="diag-title">
                您确定拥有《遇见未知的自己》这本书吗？</h5>
            <p id="modal1Desc" class="description-font">
                如果您不想赠送此书，或者没有这本书，请不要随意发布虚假信息。谢谢你的支持和理解。
            </p>
        </div>
        <br>
        <button data-remodal-action="confirm" class="remodal-confirm">确定赠送</button>
        <button data-remodal-action="cancel" class="remodal-cancel">不，算了</button>
    </div>

</div>
<div id="footer" class="flex-hor-center">
    <span>© 2017-2020 yushu.im created by 七月</span>
</div>
</body>



    <script src="/static/3rd/jquery-3.2.1.min.js"></script>
    <script src="/static/3rd/bootstrap.min.js"></script>
    <script src="/static/js/base.js"></script>
    <script>
        $SCRIPT_ROOT = "";
    </script>

    <script src="/static/3rd/remodal.min.js"></script>
    <script src="/static/js/book-detail.js"></script>


</html>

yushu/templates/book/drift.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>


    <title>鱼书</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">




    <link rel="stylesheet"
          href="/static/3rd/ui/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="shortcut icon"
          href="/static/images/icon.png">

    <link rel="stylesheet" href="/static/css/drift.css">


<body>


<div class='container'>
    <div class="row">




    </div>

    <div style="margin-top:100px;" class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="row">
                <div class="col-md-2">
                    <a id='nav_url' href="/">去首页</a>
                </div>
            </div>
            <div class="bg-container">
                <div class="row">
                    <div class="col-md-12 text-center bg-head">
                        <span class="drift-title">向<span
                                class="space">苦海翻起爱恨</span>请求这本书</span>
                    </div>
                </div>
                <div style="margin-top:15px;" class="row">
                    <div class="col-md-10 col-md-offset-1 flex-vertical gifter-container">
                        <span class="sub-title-color">以下是书籍拥有者信息，诚信度供你参考:</span>
                        <span style="margin-top:10px; margin-bottom:10px;">苦海翻起爱恨</span>
                        <div><span
                                class="description-font">鱼豆：</span><span>0.0</span>
                        </div>
                        <div><span
                                class="description-font">接受/送出书籍：</span><span>0/0</span>
                        </div>
                    </div>
                </div>
                <div style="margin-top:10px;" class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <span class="main-color">本次交易将消耗你1个鱼豆，你当前还有2.5个鱼豆</span>
                    </div>
                </div>
                <form action="" method="post">
                    <div style="margin-top:20px;" class="row">
                        <div class="col-md-10 col-md-offset-1 flex-vertical input-margin">
                            <label class="sub-title-color" for="recipient_name">收件人姓名</label>
                            <div class="row">
                                <div class="col-md-5">
                                    <input placeholder="请填写收件人姓名" id="recipient_name"
                                           name="recipient_name"
                                           class="normal-input btn-block form-control"
                                           value="">
                                </div>
                            </div>
                            <label class="sub-title-color" for="mobile">联系电话</label>
                            <div class="row">
                                <div class="col-md-5">
                                    <input placeholder="如13818181818" id="mobile"
                                           name="mobile"
                                           class="normal-input btn-block form-control"
                                           value="">
                                </div>
                            </div>
                            <label class="sub-title-color" for="address">书籍收件地址</label>
                    <textarea class="form-control" rows="3" id="address" name="address"
                              placeholder="如，张三 北京市清华大学666室。请务必确保该地址能够收到书籍"></textarea>
                            <label class="sub-title-color" for="message">对他 / 她
                                说的话</label>
                        <textarea class="form-control" id="message" name="message"
                                  rows="4"
                                  placeholder="如有一些特别的要求，可以在这里填写"></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div style="position: relative;left:-20px;"
                             class="col-md-5 col-md-offset-4 flex-vertical text-center">
                            <input style="margin-top:12px;" type="submit"
                                   class="btn btn-big btn-block" value="提交">
                        <span style="margin-top:15px;"
                              class="main-color">提交信息，等待苦海翻起爱恨将书籍邮寄给你</span>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<div id="footer" class="flex-hor-center">
    <span>© 2017-2020 yushu.im created by 七月</span>
</div>
</body>


    <script src="/static/3rd/jquery-3.2.1.min.js"></script>
    <script src="/static/js/drift.js"></script>


</html>

yushu/templates/index_home.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>


    <title>鱼书</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="shortcut icon" href="{% static 'picture/icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">




<body>
{#登录注册搜索开始#}
    <div class="nav-self">
        <div style="padding-top: inherit" class="container">
            {#搜索跳转#}
            <form class="form-inline" action="/book/search" method="get">
                <div class="flex-vertical-center-height">
                    <div class="col-md-2  col-xs-3 logo">
                        <img src="{% static 'picture/logo-yushu.png' %}"/>
                    </div>
                    <div style="margin-left:20px;" class="col-md-7  col-xs-6 input-group">
                        <input name="q" type="text" placeholder="ISBN、图书名称"
                               class="form-control input-sm">
                        <span class="input-group-btn">
                            <input class="btn btn-search" type="submit" value="搜索"/>
                        </span>
                    </div>
                    <div class="col-md-3 col-xs-3" style="padding-right: 0">




                        <div class="container-height flex-vertical-center login-box">
                            
                                <div style="height: 100%; width: 100%;display: flex; justify-content: flex-end; align-items: center">
                                    {% if username %}
                                    <a href="/personal">{{ username }}</a>
                                    <a class="btn-end" href="/logout">注销</a>
                                    {% else %}
                                    <a href="{% url 'App:index_login' %}">登录</a>
                                    <a class="btn-end" href="{% url 'App:index_register' %}">注册</a>
                                    {% endif %}
                                </div>
                            
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{#登录注册结束#}
{#导航栏开始#}
    <div class="sub-nav flex-vertical-center">
        <div class="container" style="width: 100%">
            <div class="row">
                <div class="col-md-2 col-xs-3 col-md-offset-2">
                    <a id="recent" href="/"
                       class="flex-vertical-hor-center">
                        <img src="picture/upload.png"/>
                        <span>最近上传</span>
                    </a>
                </div>
                <div class="col-md-2 col-xs-3">
                    <a id="gifts" href="/my/gifts"
                       class="flex-vertical-hor-center">
                        <img src="picture/gift.png"/>
                        <span>赠送清单</span>
                    </a>
                </div>
                <div class="col-md-2 col-xs-3">
                    <a id="wishes" href="/my/wish"
                       class="flex-vertical-hor-center">
                        <img src="picture/wish.png"/>
                        <span>心愿清单</span>
                    </a>
                </div>
                <div class="col-md-2 col-xs-3">
                    <a id="pending" href="/pending"
                       class="flex-vertical-hor-center">
                        <img src="picture/fish.png"/>
                        <span>鱼漂</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
{#导航栏结束#}


<div class='container'>
    <div class="row">

    </div>
    
    <div class="row">
        <div class="col-md-12">
        </div>
    </div>

    <div id="books" class="row">
            {#图书展示开始#}
            <div class="col-sm-4 book-container">
                <a href="/book/9787508044019/detail" class="link">
                    <div class="col-md-4 no-padding">
                        <img class="book-img cssshadow" src="../static/picture/s3403254.jpg">
                    </div>
                    <div style="margin-left: 0;" class="col-md-8 flex-vertical book-info">
                        <span class="title">遇见未知的自己</span>
                        <div class="description-font"><span>作者：</span><span>张德芬</span>
                        </div>
                        <span class="summary description-font">故事从“冬天的雨夜，在荒郊野外的山区，一个没有手机、没有汽油的孤单女人”开始。\n若菱，自名校毕业，拥有令人羡慕的工作，但心中却不时的自问：为什么我不能拥有想要的生活？为什么我不快乐？我该如何当自己生命的主人？ 在一个下雨的冬夜，若菱巧遇一名智慧老者，在与智者数度交谈的过程中，她渐渐填补不快乐、挫败的心灵缺口，寻回最真实勇敢的自我…… 你会不会担心和若菱一样，让身体的疲惫失控于华丽的业绩之中？ 你是否也想遇见在你心中的智慧老者，穿越心事的重重黑纱，遇见全新的自己？</span>
                    </div>
                </a>
            </div>

            {#图书展示结束#}

        
    </div>

</div>



<div id="footer" class="flex-hor-center">
    <span>© 2017-2020 yushu.im created by 七月</span>
</div>
</body>


    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script>
        $SCRIPT_ROOT = "";
    </script>


</html>

yushu/templates/index_login.html
{% load staticfiles %}
{% csrf_token %}
<!DOCTYPE HTML>
<html>


    <title>鱼书</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">



    
    <link rel="stylesheet"
          href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="shortcut icon" href="{% static 'picture/icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">


<body>


<div class='container'>
    <div class="row">
        
            
        
        
    </div>
    
    <div class="row white-bg-margin">
        <div class="col-md-6 col-md-offset-3">
            <div class="row">
                <div class="col-md-2">
                    <a onclick="window.history.go(-1)" href="#">返回</a>
                </div>
            </div>
            <div class="bg-container">
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 text-center">
                        <span class="big-title">鱼 书</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 flex-vertical personal-detail">
                        <form action="" method="post">
                            {% csrf_token %}
                            <input style="width:100%" id="email" name="email" type="text"
                                   placeholder="邮箱"
                                   class="none-input"
                                   value="">
                            <div style="margin-top:3px;" class="password-box">
                                <input id="password"
                                       name="password"
                                       placeholder="密码"
                                       class="none-input" type="password">
                                <a id="forget-password" class="description-font"
                                   href="/reset/password">
                                    忘记密码?</a>
                            </div>
                            <input style="margin-top:15px;" id="btn-submit" type="submit"
                                   class="btn btn-big btn-block" value="登录">
                        </form>
                    </div>
                </div>
                <div style="margin-top:30px;" class="row">
                    <div class="col-md-8 text-center col-md-offset-2">
                        <span class="description-font">没有账号？</span><a
                            href="{% url 'App:index_register' %}">注册</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<div id="footer" class="flex-hor-center">
    <span>© 2017-2020 yushu.im created by 七月</span>
</div>
</body>


    
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script>
        $SCRIPT_ROOT = "";
    </script>



</html>

yushu/templates/index_register.html
{% load staticfiles %}

<!DOCTYPE HTML>
<html>


    <title>鱼书</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="shortcut icon" href="{% static 'picture/icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">



<body>
<div class='container'>
    <div class="row">
        {% if a == 1 %}
        <div class="alert alert-warning" role="alert">[&#39;昵称不能为空，请填写昵称&#39;]</div>
        {% elif a == 2 %}
        <div class="alert alert-warning" role="alert">[&#39;昵称已经存在&#39;]</div>
        {% elif b == 1 %}
        <div class="alert alert-warning" role="alert">[&#39;邮箱不能为空&#39;]</div>
        {% elif b == 2 %}
        <div class="alert alert-warning" role="alert">[&#39;邮箱格式错误&#39;]</div>
        {% elif b == 3 %}
        <div class="alert alert-warning" role="alert">[&#39;邮箱已被注册&#39;]</div>
        {% elif c == 1 %}
        <div class="alert alert-warning" role="alert">[&#39;密码需要不少于8位字符&#39;]</div>
        {% elif c == 2 %}
        <div class="alert alert-warning" role="alert">[&#39;密码由数字和字母组成&#39;]</div>
        {% endif %}

    </div>
    
    <div class="row white-bg-margin">
        <div class="col-md-6 col-md-offset-3">
            <div class="bg-container">
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 text-center">
                        <span class="big-title">鱼 书</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 flex-vertical personal-detail">
                        {#注册提交部分#}
                        <form action="{% url 'App:index_register' %}" method="post">
                            {% csrf_token %}
                            <input style="width:100%" id="username" name="username"
                                   type="text"
                                   placeholder="昵称"
                                   class="none-input"
                                   value="">
                            <input style="width:100%" id="email" name="email" type="text"
                                   placeholder="邮箱"
                                   class="none-input"
                                   value="">
                            <input id="password" style="width:100%"
                                   name="password"
                                   placeholder="密码"
                                   class="none-input" type="password">
                            <input style="margin-top:15px;" id="btn-submit" type="submit"
                                   class="btn btn-big btn-block" value="注册">
                        </form>
                        {#注册提交部分结束#}
                    </div>
                </div>
                <div style="margin-top:30px;" class="row">
                    <div class="col-md-8 text-center col-md-offset-2">
                        <span class="description-font">已有账号？</span>
                        {#直接跳到登录界面#}
                        <a href="{% url 'App:index_login' %}">登录</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<div id="footer" class="flex-hor-center">
    <span>© 2017-2020 yushu.im created by 七月</span>
</div>
</body>


    
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script>
        $SCRIPT_ROOT = "";
    </script>



</html>

yushu/templates/user/personal.html
<!DOCTYPE HTML>
<html>


    <title>鱼书</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">



    
    <link rel="stylesheet"
          href="/static/3rd/ui/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="shortcut icon"
          href="/static/images/icon.png">

     <link rel="stylesheet" href="/static/css/personal.css">


<body>


<div class='container'>
    <div class="row">
        
            
        
        
    </div>
    
    <div class="row">
        <div style="margin-top:150px;" class="col-md-6 col-md-offset-3">
            <div class="row">
                <div class="col-md-2">
                    <a onclick="window.history.go(-1)" href="#">返回</a>
                </div>
            </div>
            <div class="bg-container">
                <div class="row">
                    <div class="col-md-4 col-md-offset-4 text-center">
                        <span class="big-title">z12z</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 flex-vertical personal-detail">
                        <div><span>送出/收到：</span><span>0/0</span></div>
                        <div><span>当前鱼豆：</span><span>0.0</span></div>
                        <div><span>登录邮箱：</span><span>1106774901@qq.com</span></div>
                        <div><span>登录密码：********* </span><a
                                href="/change/password">修改</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<div id="footer" class="flex-hor-center">
    <span>© 2017-2020 yushu.im created by 七月</span>
</div>
</body>


    <script src="/static/3rd/jquery-3.2.1.min.js"></script>
    <script src="/static/3rd/bootstrap.min.js"></script>
    <script src="/static/js/base.js"></script>
    <script>
        $SCRIPT_ROOT = "";
    </script>


</html>